Wip/w 499
project-tsurugi/tsubakuro pull request #398
Opened 2023-12-28 08:16 UTC by t-horikawa

https://github.com/project-tsurugi/tsurugi-issues/issues/499

2024-01-10 23:16 UTC, ashigeru requested changes

2024-01-10 23:16 UTC, ashigeru commented on modules/ipc/src/test/java/com/tsurugidb/tsubakuro/channel/ipc/sql/ServerWireImpl.java
> +                e.printStackTrace();
例外を握りつぶしているため、接続エラー時の分析が困難になります (とくに、このタイミングで認証エラーが出るのでそれを拾えないのは致命的ではないでしょうか)。
例外を接続元に返せるように以下のいずれかの変更が必要です。

1. `RuntimeException` を継承したクラスを作成し、このスレッドでは例外そのクラスでラップして投げておいて、[Thread.setUncaughtExceptionHandler](https://docs.oracle.com/javase/jp/8/docs/api/java/lang/Thread.html#setUncaughtExceptionHandler-java.lang.Thread.UncaughtExceptionHandler-) 等を利用して取り出す
2. 例外を投げられるように `Callable` 等でクラスを作成し、 `ExecutorService.submit()` 等で処理を実行する。

2024-01-10 23:16 UTC, ashigeru commented on modules/ipc/src/test/java/com/tsurugidb/tsubakuro/channel/ipc/sql/ServerWireImpl.java
> +        this.receiver = new ReceiveWorker();
処理の性質を考えると、これは daemon thread にしておくのが妥当ではないでしょうか。
この実装では、handshake の応答がない際にクライアントに割り込みを入れると、クライアントプロセスが終了しないように思います

2024-01-10 23:16 UTC, ashigeru commented on modules/ipc/src/test/java/com/tsurugidb/tsubakuro/channel/ipc/sql/ServerWireImpl.java
> +                throw new IOException(e);
IOException をキャッチした際に余計に IOException でくるんでいます。
また、 InterruptedException を IOException でくるんでしまうと、割り込みが発生したという情報が正しく上位に伝えられず、不適切にリカバリしてしまうのではないでしょうか。

2024-01-10 23:16 UTC, ashigeru commented on modules/ipc/src/test/java/com/tsurugidb/tsubakuro/channel/ipc/sql/ServerWireImpl.java
> +                    throw new IOException("error: sessionWireHandle is 0");
例外メッセージが不適切です。
利用者が読んでわかるような情報を付帯してください、

他のすべての例外も同様にお願いします。

2024-01-10 23:16 UTC, ashigeru commented on modules/proto/src/main/protos/tateyama/proto/endpoint/request.proto
> +    auth.request.AuthInfo auth_info = 1;
サービス階層的に、 `auth.request.AuthInfo` を利用するのは不適切です。
現在は空でも構いませんので、 `Credential` というメッセージを作って将来的にJavaの同名のクラスの内容を含められるようにしてください。

2024-01-10 23:16 UTC, ashigeru commented on modules/proto/src/main/protos/tateyama/proto/endpoint/request.proto
> +    string user_name = 4;
ユーザ名はCredential とは不可分です。
そのため、ここから取り除くか ClientInformation の中に Credential を含めてください。

2024-01-10 23:16 UTC, ashigeru commented on modules/proto/src/main/protos/tateyama/proto/endpoint/request.proto
> +    uint64 maximum_concurrent_result_sets = 11;
このフィールドだけ `ClientInformaiton` なのかどうか怪しいです。
どちらかというと configuration に思いますが、どのような位置づけでしょうか。
場合によっては一つ上の階層である `Handshake` に直接書くのがいいのかもしれません。

2024-01-10 23:16 UTC, ashigeru commented on modules/session/src/main/java/com/tsurugidb/tsubakuro/common/SessionBuilder.java
> +    private ClientInformation clientInformation = new ClientInformation();
ClientInformationの個所に書きましたが、こいつは不変クラスとすべきに思います。
そのため、ここで new するのではなく、`create` のタイミングがよさそうです。

2024-01-15 08:15 UTC, t-horikawa commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ClientInformation.java
> +    private long maxResultSets;  // used by Stream
Done

2024-01-15 08:16 UTC, t-horikawa commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ClientInformation.java
> +    public ClientInformation() {
Done

2024-01-15 08:16 UTC, t-horikawa commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ClientInformation.java
> +    public String connectionLabel() {
done

2024-01-15 08:16 UTC, t-horikawa commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ClientInformation.java
> +        return "";
done

2024-01-15 08:17 UTC, t-horikawa commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ClientInformation.java
> +    public long maximumConcurrentResultSets() {
Done（setterを取り除きました）

2024-01-15 08:18 UTC, t-horikawa commented on modules/ipc/src/test/java/com/tsurugidb/tsubakuro/channel/ipc/sql/ServerWireImpl.java
> +                    throw new IOException("error: sessionWireHandle is 0");
この部分はtestなので、testをfail()させるようにしました。

2024-01-15 08:18 UTC, t-horikawa commented on modules/proto/src/main/protos/tateyama/proto/endpoint/request.proto
> +    auth.request.AuthInfo auth_info = 1;
Done

2024-01-15 08:19 UTC, t-horikawa commented on modules/proto/src/main/protos/tateyama/proto/endpoint/request.proto
> +    uint64 maximum_concurrent_result_sets = 11;
Done

2024-01-15 08:19 UTC, t-horikawa commented on modules/session/src/main/java/com/tsurugidb/tsubakuro/common/SessionBuilder.java
> +    private ClientInformation clientInformation = new ClientInformation();
Done

2024-01-15 08:38 UTC, t-horikawa commented on modules/proto/src/main/protos/tateyama/proto/endpoint/request.proto
> +    string user_name = 4;
request.protoは修正しましたが、userNameを渡すパスの実装が適切かどうかは自信がありません。
「ここから取り除く」 && 「ClientInformation の中に Credential を含める」としました（コメントでは||でしたが）。

2024-01-16 01:13 UTC, ashigeru requested changes
残件と合わせて確認お願いします。

2024-01-16 01:13 UTC, ashigeru commented on modules/proto/src/main/protos/tateyama/proto/endpoint/request.proto
> +    Credential credential = 1;
Credential を二重に渡しているので、どちらか一つでよさそうです。

2024-01-16 01:13 UTC, ashigeru commented on modules/session/src/main/java/com/tsurugidb/tsubakuro/common/SessionBuilder.java
> +    public SessionBuilder withUserName(@Nonnull String userNameString) {
認証されないユーザー名を渡してもあまり意味がないので、この関数は不要に思います。

2024-01-16 01:14 UTC, ashigeru commented on modules/ipc/src/test/java/com/tsurugidb/tsubakuro/channel/ipc/sql/ServerWireImpl.java
> +    private class ReceiveWorker extends Thread {
ここ test ですね。無視してかまいません。

2024-01-16 01:14 UTC, ashigeru commented on modules/ipc/src/test/java/com/tsurugidb/tsubakuro/channel/ipc/sql/ServerWireImpl.java
> +                e.printStackTrace();
ここ test ですね。無視してかまいません。

2024-01-16 01:14 UTC, ashigeru commented on modules/ipc/src/test/java/com/tsurugidb/tsubakuro/channel/ipc/sql/ServerWireImpl.java
> +        this.receiver = new ReceiveWorker();
ここ test ですね。無視してかまいません。

2024-01-16 01:15 UTC, ashigeru commented on modules/ipc/src/test/java/com/tsurugidb/tsubakuro/channel/ipc/sql/ServerWireImpl.java
> +                throw new IOException(e);
ここ test ですね。無視してかまいません。

2024-01-16 06:54 UTC, t-horikawa commented on modules/session/src/main/java/com/tsurugidb/tsubakuro/common/SessionBuilder.java
> +    public SessionBuilder withUserName(@Nonnull String userNameString) {
Done

2024-01-16 06:56 UTC, t-horikawa commented on modules/proto/src/main/protos/tateyama/proto/endpoint/request.proto
> +    Credential credential = 1;
Done

2024-01-16 06:57 UTC, t-horikawa commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ClientInformation.java
> + * A credential by user name and password.
Done

2024-01-16 06:57 UTC, t-horikawa commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ClientInformation.java
> +    private String userName;
Done

2024-01-16 06:59 UTC, t-horikawa commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/Connector.java
> +    FutureResponse<Wire> connect(@Nonnull Credential credential, @Nonnull ClientInformation clientInformation) throws IOException;
Done

2024-01-16 07:04 UTC, t-horikawa commented on modules/ipc/src/main/java/com/tsurugidb/tsubakuro/channel/ipc/connection/IpcConnectorImpl.java
> +            clientInformation.connectionInformation(Long.toString(ProcessHandle.current().pid()));
「EndpointRequest.Handshake オブジェクト構築」のタイミングは異なりますが、pidの情報はclientInformationとは別にしています。

2024-01-16 07:04 UTC, t-horikawa commented on modules/stream/src/main/java/com/tsurugidb/tsubakuro/channel/stream/connection/StreamConnectorImpl.java
> +        clientInformation.maximumConcurrentResultSets(ResponseBox.responseBoxSize());
Done

2024-01-16 07:04 UTC, t-horikawa commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/WireImpl.java
> +                    .setMaximumConcurrentResultSets(clientInformation.maximumConcurrentResultSets()));
Done

2024-01-17 01:43 UTC, ashigeru approved these changes
一か所マイナーな修正だけ入れてもらって、あとはOKです。

2024-01-17 01:43 UTC, ashigeru commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ClientInformation.java
> +        this.connectionLabel = connectionLabel;
`Objects.requireNonNull(credential)` を入れといてください

2024-01-17 01:43 UTC, ashigeru commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/WireImpl.java
> +                    break;
別のエラーもありそうなので、 `newUnknown()` にしといたほうが無難かもしれません。

2024-01-17 01:43 UTC, ashigeru commented on modules/ipc/src/main/java/com/tsurugidb/tsubakuro/channel/ipc/connection/IpcConnectorImpl.java
> +            clientInformation.connectionInformation(Long.toString(ProcessHandle.current().pid()));
OK

2024-01-18 09:50 UTC, t-horikawa commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ClientInformation.java
> +        this.connectionLabel = connectionLabel;
Done

2024-01-18 09:51 UTC, t-horikawa commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/wire/impl/WireImpl.java
> +                    break;
newUnknown()が用意されていなかったので新設し、newUnknown(message.getError())をnewUnknown()に変更しました。

2024-01-19 02:08 UTC, merged