add functionality to accept setCloseTimeout() in ForegroundFutureResp…
project-tsurugi/tsubakuro pull request #427
Opened 2024-04-23 09:27 UTC by t-horikawa

https://github.com/project-tsurugi/tsurugi-issues/issues/762

2024-04-23 09:31 UTC, t-horikawa commented
@hishidama ForegroundFutureResponseのsetCloseTimeout()を対処しました。お手数ですが、reviewをお願いします。

2024-04-24 23:43 UTC, hishidama requested changes

2024-04-24 23:43 UTC, hishidama commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
>                  var obj = get();
get()がタイムアウトしないので、close()自体がタイムアウトしない可能性があります。
（自分が今回の問題を発見したきっかけは、ここのget()から返らないことでした）

（そもそも、closeの中でgetを呼ばないのが望ましいですが）

2024-04-24 23:43 UTC, hishidama commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
>              Owner.close(unprocessed.getAndSet(null));
unprocessed.getAndSet(null)は（上でupという変数に代入されたので）upという変数を使うべきだと思います。
（でないと、ここでは常にnullになってしまうのでは？）

2024-04-24 23:43 UTC, hishidama commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
>                      ((ServerResource) obj).close();
何度もobjをServerResourceにキャストするのも冗長なので、ServerResourceの変数に代入して、それを使い回す方が良いと思います。

2024-04-24 23:43 UTC, hishidama commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
> +                    if (closeTimeout != null) {
setCloseTimeoutの引数がNonnullなのでnullチェックをして代入していると思いますが、
Nullableにして、nullチェック無しで常に代入してもいいような気がします。

（setCloseTimeoutでユーザーがnullを指定できてもよいのではないかと思います（明示的にタイムアウトさせないという意味になると思われます。…あまりしないとは思いますが））

2024-04-25 00:25 UTC, t-horikawa commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
>              Owner.close(unprocessed.getAndSet(null));
確かに、これはまずい。

2024-04-25 00:30 UTC, t-horikawa commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
>                  var obj = get();
「getを呼ばない」は繰り返し指摘されていますが、tateyamaがresponseメッセージを送ってくる（可能性がある）ので、それを放置することはできないと思っています。Sessionを閉じるときの処理であれば、「後はどうなっても構わない」という想定で放置できるかもしれませんが、この後もtateyamaとのやり取りする可能性があるはずなので、careは必要かと。

2024-04-25 00:31 UTC, t-horikawa commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
> +                    if (closeTimeout != null) {
大元のsetCloseTimeout()仕様を確認します。

2024-04-25 01:45 UTC, t-horikawa commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
> +                    if (closeTimeout != null) {
ここのsetCloseTimeout()はNullableにできますが、大元のServerResourceのsetCloseTimeout()は@Nunnullとなっているので、呼ぶ先はnullを受け入れないようになっている可能性があります。なので、nullチェックは残します。

2024-04-26 01:32 UTC, hishidama commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
>                  var obj = get();
close内でget()を呼ぶことの是非については、このプルリクエストでは対象外でいいです。

問題は、引数無しのget()ではタイムアウトしないことです。

2024-04-26 02:31 UTC, hishidama requested changes

2024-04-26 02:31 UTC, hishidama commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
> +                        throw new IOException(e);
IOExceptionでなく、ResponseTimeoutExceptionが望ましいです。
（Iceaxeでは、TimeoutExceptionとResponseTimeoutExceptionをタイムアウトとして識別している為）

2024-04-26 02:31 UTC, hishidama commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
>          } finally {
そういえば、finallyで例外が発生したら、try本体で発生した例外が消されてしまいますね。

2024-04-26 09:07 UTC, t-horikawa commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
>          } finally {
対処しました（close()が３か所になると急に面倒になる感じ）。

2024-04-30 00:04 UTC, hishidama requested changes

2024-04-30 00:04 UTC, hishidama commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/BackgroundFutureResponse.java
>          try {
try本体で発生しうる例外はResponseTimeoutExceptionだけでなく、IOException・InterruptException・ServerException・RuntimeException（・Error）も考えられます。

2024-04-30 00:25 UTC, t-horikawa commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/BackgroundFutureResponse.java
>          try {
了解。こちらもForegroundFutureResponseと同様にしておきます。

2024-05-10 07:08 UTC, hishidama requested changes

2024-05-10 07:08 UTC, hishidama commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
> +                throwException(exception);
元のexceptionがnull以外だった場合は既にスローされている状態なので、改めてスローする必要は無いです。(元のexceptionがnullのときだけスローする）

もしくは、tryやfinallyの途中ではスローせず、最後にexceptionがnull以外の時だけスローする。

2024-05-10 07:59 UTC, t-horikawa commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
> +                throwException(exception);
> tryやfinallyの途中ではスローせず、最後にexceptionがnull以外の時だけスローする

なるほど、それで良いのか。単純になりました。

2024-05-13 00:46 UTC, t-horikawa commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
> +                    } catch (TimeoutException e) {
Done

2024-05-13 00:46 UTC, t-horikawa commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
> +                        sr.close();
Done

2024-05-13 00:46 UTC, t-horikawa commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
> +            } catch (IOException | ServerException | InterruptedException e) {
Done

2024-05-23 01:22 UTC, hishidama commented on modules/common/src/main/java/com/tsurugidb/tsubakuro/channel/common/connection/ForegroundFutureResponse.java
>                  delegate.get().cancel();
このget()およびcancel)は、タイムアウトしますか？

2024-06-13 07:14 UTC, hishidama approved these changes
LGTM

2024-06-13 08:28 UTC, merged